// The periodic wake-up.
//
// A PWA cannot schedule itself: a service worker only runs when a push
// arrives. So the "check what's due" part of the app lives here instead of on
// the phone. pg_cron calls this every 15 minutes; for every task, it works out
// whose reminder time has just passed - the assignee's if the task has one,
// otherwise everyone in the space - and pushes only to them.
//
// Running server-side has a side benefit over an on-device timer: a reminder
// still fires for someone who has not opened the app in weeks, and is not at
// the mercy of Android's battery optimiser.

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.4'
import { classify, formatTimeIn, minutesOfDayIn, todayIn, type DueTask } from '../_shared/taskDue.ts'
import { loadConfig } from '../_shared/config.ts'
import { composeReminder, composeTimeLimitedReminder, isLanguage, type Language } from '../_shared/messages.ts'
import { planSnoozeOutcomes, type ExpiredSnooze, type SnoozeTask } from '../_shared/snoozeResend.ts'
import { dueReminderSlots, type ReminderPolicy } from '../_shared/timeLimitedReminders.ts'
import { sendPush, type PushTarget } from '../_shared/webpush.ts'

interface Profile {
  id: string
  display_name: string | null
  timezone: string
  language: Language | null
}

interface Task extends DueTask {
  id: string
  space_id: string
  title: string
  reminder_hour: number
  reminder_minute: number
  assigned_to: string | null
  reminder_policy: ReminderPolicy | null
}

interface Subscription extends PushTarget {
  id: string
  user_id: string
  failure_count: number
}

// How long after a task's chosen time we will still deliver. Wide enough to
// absorb cron jitter and a cold start; the per-day log stops it repeating.
const WINDOW_MINUTES = Number(Deno.env.get('REMINDER_WINDOW_MINUTES') ?? '60')
const admin = createClient(
  Deno.env.get('SUPABASE_URL') ?? '',
  Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
  { auth: { persistSession: false } },
)

/**
 * Sends one push to every one of a person's subscriptions, updating each
 * subscription row the same way regardless of who called this - the periodic
 * reminder and a snoozed-task resend both need identical bookkeeping on
 * success, a dead endpoint, and a transient failure.
 */
async function pushToSubscriptions(
  subs: Subscription[],
  payload: unknown,
  vapid: Parameters<typeof sendPush>[2],
): Promise<number> {
  let sent = 0
  for (const sub of subs) {
    const result = await sendPush(sub, payload, vapid)
    if (result.ok) {
      sent++
      await admin
        .from('push_subscriptions')
        .update({ last_sent_at: new Date().toISOString(), failure_count: 0 })
        .eq('id', sub.id)
    } else if (result.gone) {
      // The browser has forgotten this subscription; stop writing to it.
      await admin.from('push_subscriptions').delete().eq('id', sub.id)
    } else {
      console.error('push failed', sub.endpoint.slice(0, 60), result.status, result.detail)
      await admin
        .from('push_subscriptions')
        .update({ failure_count: sub.failure_count + 1 })
        .eq('id', sub.id)
    }
  }
  return sent
}

Deno.serve(async (request) => {
  const config = await loadConfig(admin)
  if (!config) {
    return new Response(JSON.stringify({ error: 'not_configured' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  // Deployed with --no-verify-jwt (pg_cron has no user session), so the shared
  // secret is what keeps this endpoint from being a free push cannon. The
  // secret is generated by the setup SQL; nobody ever types it.
  if (request.headers.get('x-cron-secret') !== config.cronSecret) {
    return new Response(JSON.stringify({ error: 'forbidden' }), {
      status: 403,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  const url = new URL(request.url)
  // `?dry=1` runs the whole selection and reports who *would* be notified,
  // without sending or writing the log. Handy when checking the setup.
  const dryRun = url.searchParams.get('dry') === '1'
  const now = new Date()
  const nowIso = now.toISOString()

  const [profiles, subscriptions, memberships, tasks, spaces, snoozes] = await Promise.all([
    admin.from('profiles').select('id, display_name, timezone, language'),
    admin.from('push_subscriptions').select('id, user_id, endpoint, p256dh, auth, failure_count'),
    admin.from('space_members').select('space_id, user_id'),
    admin
      .from('tasks')
      .select(
        'id, space_id, title, task_type, recurrence_mode, interval_days, weekly_days, ' +
          'end_condition, end_after_count, end_date, occurrences_completed, due_date, ' +
          'last_completed_date, is_done, reminder_hour, reminder_minute, assigned_to, ' +
          'starts_at, expires_at, reminder_policy, cancelled_at, expired_at',
      )
      .eq('is_done', false),
    admin.from('spaces').select('id, name'),
    admin.from('task_snoozes').select('task_id, user_id, snoozed_until'),
  ])

  const failed = [profiles, subscriptions, memberships, tasks, spaces, snoozes].find((r) => r.error)
  if (failed?.error) {
    console.error('load failed', failed.error)
    return new Response(JSON.stringify({ error: failed.error.message }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  const subsByUser = new Map<string, Subscription[]>()
  for (const sub of (subscriptions.data ?? []) as Subscription[]) {
    const list = subsByUser.get(sub.user_id) ?? []
    list.push(sub)
    subsByUser.set(sub.user_id, list)
  }

  const membersBySpace = new Map<string, string[]>()
  for (const row of memberships.data ?? []) {
    const list = membersBySpace.get(row.space_id) ?? []
    list.push(row.user_id)
    membersBySpace.set(row.space_id, list)
  }

  const tasksById = new Map<string, Task>((tasks.data ?? []).map((t: Task) => [t.id, t]))
  const profilesById = new Map<string, Profile>(
    ((profiles.data ?? []) as Profile[]).map((profile) => [profile.id, profile]),
  )
  const spaceNames = new Map<string, string>(
    (spaces.data ?? []).map((s: { id: string; name: string }) => [s.id, s.name]),
  )

  // Which (task, user) pairs are currently snoozed - suppress them here; the
  // expired-snooze pass below is what resends once the timer runs out.
  const activeSnooze = new Set<string>()
  for (const row of (snoozes.data ?? []) as { task_id: string; user_id: string; snoozed_until: string }[]) {
    if (row.snoozed_until > nowIso) activeSnooze.add(`${row.task_id}:${row.user_id}`)
  }

  // Every user who should be considered for a task: the assignee alone if the
  // task has one, otherwise every member of its space.
  const tasksForUser = new Map<string, Task[]>()
  for (const task of tasksById.values()) {
    const targets = task.assigned_to ? [task.assigned_to] : (membersBySpace.get(task.space_id) ?? [])
    for (const userId of targets) {
      const list = tasksForUser.get(userId) ?? []
      list.push(task)
      tasksForUser.set(userId, list)
    }
  }

  const report: Record<string, unknown>[] = []
  let sentCount = 0

  for (const [userId, userTasks] of tasksForUser) {
    const profile = profilesById.get(userId)
    if (!profile) continue
    const subs = subsByUser.get(userId)
    if (!subs?.length) continue // nothing to push to

    const localDate = todayIn(profile.timezone, now)
    const nowMinutes = minutesOfDayIn(profile.timezone, now)

    const dueNow = userTasks
      .map((task) => ({ task, info: classify(task, localDate) }))
      .filter(({ task, info }) => {
        // Time-limited tasks have their own cadence and dedup below - this
        // loop's once-a-day notification_log key cannot tell two of their
        // reminders on the same day apart.
        if (task.task_type === 'time_limited') return false
        if (!info.notifiable) return false
        if (activeSnooze.has(`${task.id}:${userId}`)) return false
        const taskMinutes = task.reminder_hour * 60 + task.reminder_minute
        const sinceDue = nowMinutes - taskMinutes
        return sinceDue >= 0 && sinceDue < WINDOW_MINUTES
      })
      .sort((a, b) => b.info.daysLate - a.info.daysLate)

    if (dryRun) {
      if (dueNow.length) {
        report.push({
          user: profile.display_name ?? userId,
          localDate,
          wouldNotify: dueNow.map(({ task }) => task.title),
        })
      }
      continue
    }

    if (!dueNow.length) continue

    // Claim each task for this user+day; the primary key on
    // (user_id, task_id, local_date) is the whole duplicate-suppression
    // mechanism - two overlapping cron runs race here, and exactly one wins.
    const claimed: { task: Task; daysLate: number }[] = []
    for (const { task, info } of dueNow) {
      const claim = await admin
        .from('notification_log')
        .insert({ user_id: userId, task_id: task.id, local_date: localDate, kind: 'due' })
        .select('user_id')
      if (claim.error || !claim.data?.length) continue // already handled today
      claimed.push({ task, daysLate: info.daysLate })
    }
    if (!claimed.length) continue

    const language: Language = isLanguage(profile.language) ? profile.language : 'he'
    const userSpaceCount = new Set(claimed.map(({ task }) => task.space_id)).size

    const { title, body } = composeReminder(
      claimed.map(({ task, daysLate }) => ({
        name: task.title,
        spaceName: userSpaceCount > 1 ? (spaceNames.get(task.space_id) ?? '?') : undefined,
        daysLate,
      })),
      language,
    )

    const payload = {
      title,
      body,
      lang: language,
      dir: language === 'he' ? 'rtl' : 'ltr',
      // One tag per day means a re-delivery replaces the old notification in
      // the tray rather than stacking a second copy.
      tag: `househero-${localDate}`,
      spaceId: claimed[0].task.space_id,
      taskId: claimed.length === 1 ? claimed[0].task.id : undefined,
      taskCount: claimed.length,
    }

    sentCount += await pushToSubscriptions(subs, payload, config.vapid)
  }

  // Snoozed tasks whose timer has run out - independent of the per-task loop
  // above, since a snooze is a promise to notify again at a specific moment,
  // not at the next scheduled time.
  const expiredSnoozes = await admin
    .from('task_snoozes')
    .select('task_id, user_id')
    .lte('snoozed_until', nowIso)
  if (expiredSnoozes.error) {
    console.error('loading expired snoozes failed', expiredSnoozes.error)
  } else if (expiredSnoozes.data?.length) {
    const expired: ExpiredSnooze[] = expiredSnoozes.data.map(
      (row: { task_id: string; user_id: string }) => ({ taskId: row.task_id, userId: row.user_id }),
    )
    const snoozeTasksById = new Map<string, SnoozeTask>(
      [...tasksById.values()].map((t) => [t.id, t as SnoozeTask]),
    )
    const outcomes = planSnoozeOutcomes(
      expired,
      snoozeTasksById,
      (userId) => {
        const profile = profilesById.get(userId)
        return profile ? todayIn(profile.timezone, now) : null
      },
      (userId) => {
        const profile = profilesById.get(userId)
        return profile && isLanguage(profile.language) ? profile.language : 'he'
      },
    )

    for (const outcome of outcomes) {
      if (dryRun) {
        report.push({ snoozeResend: outcome })
        continue
      }

      // Claim by deleting first: an atomic delete is the mutex against two
      // overlapping cron runs both trying to resend the same snooze - only
      // whichever request actually removes the row gets to act on it.
      const claim = await admin
        .from('task_snoozes')
        .delete()
        .eq('task_id', outcome.taskId)
        .eq('user_id', outcome.userId)
        .lte('snoozed_until', nowIso)
        .select('task_id')
      if (!claim.data?.length) continue // another run already claimed it
      if (outcome.kind === 'stale') continue // just needed clearing, nothing to send

      const subs = subsByUser.get(outcome.userId)
      if (!subs?.length) continue

      const task = tasksById.get(outcome.taskId)
      sentCount += await pushToSubscriptions(
        subs,
        {
          title: outcome.title,
          body: outcome.body,
          lang: outcome.language,
          dir: outcome.language === 'he' ? 'rtl' : 'ltr',
          tag: `househero-snooze-${outcome.taskId}`,
          spaceId: task?.space_id ?? null,
          taskId: outcome.taskId,
          taskCount: 1,
        },
        config.vapid,
      )
    }
  }

  // Time-limited tasks: their own reminder cadence (see
  // _shared/timeLimitedReminders.ts) and their own dedup table, since more
  // than one of their reminders can land on the same calendar day - and the
  // moment their window closes, one push cannot substitute for the other.
  const timeLimitedTasks = [...tasksById.values()].filter((t) => t.task_type === 'time_limited' && t.expires_at)

  const justExpiredIds = timeLimitedTasks
    .filter((t) => new Date(t.expires_at as string).getTime() <= now.getTime())
    .map((t) => t.id)
  if (justExpiredIds.length && !dryRun) {
    const sweep = await admin
      .from('tasks')
      .update({ is_done: true, expired_at: nowIso })
      .in('id', justExpiredIds)
      .eq('is_done', false) // never overwrite a completion/cancellation that beat the sweep to it
    if (sweep.error) console.error('expiring time-limited tasks failed', sweep.error)
  } else if (justExpiredIds.length) {
    report.push({ wouldExpire: justExpiredIds })
  }

  for (const task of timeLimitedTasks) {
    if (justExpiredIds.includes(task.id)) continue

    const targets = task.assigned_to ? [task.assigned_to] : (membersBySpace.get(task.space_id) ?? [])
    for (const userId of targets) {
      const profile = profilesById.get(userId)
      const subs = subsByUser.get(userId)
      if (!profile || !subs?.length) continue

      // A daily cadence fires by this recipient's own local wall-clock time,
      // so - unlike the interval/start-only modes, both a fixed offset from
      // startsAt's absolute instant - the slot computation itself needs
      // their timezone, not just the delivery check.
      const slots = dueReminderSlots(
        { id: task.id, startsAt: task.starts_at as string, expiresAt: task.expires_at as string, reminderPolicy: task.reminder_policy },
        now,
        WINDOW_MINUTES,
        profile.timezone,
      )
      if (!slots.length) continue

      for (const slot of slots) {
        if (dryRun) {
          report.push({ timeLimited: { user: profile.display_name ?? userId, task: task.title, slot: slot.slot } })
          continue
        }

        // Same claim-by-insert mutex as notification_log above, just keyed
        // by this reminder's own instant instead of a calendar day.
        const claim = await admin
          .from('time_limited_reminder_log')
          .insert({ user_id: userId, task_id: task.id, slot: slot.slot })
          .select('user_id')
        if (claim.error || !claim.data?.length) continue // already sent

        const language: Language = isLanguage(profile.language) ? profile.language : 'he'
        const untilTime = formatTimeIn(profile.timezone, task.expires_at as string)
        const { title, body } = composeTimeLimitedReminder(task.title, untilTime, language)
        sentCount += await pushToSubscriptions(
          subs,
          {
            title,
            body,
            lang: language,
            dir: language === 'he' ? 'rtl' : 'ltr',
            tag: `househero-timelimited-${task.id}`,
            spaceId: task.space_id,
            taskId: task.id,
            taskCount: 1,
          },
          config.vapid,
        )
      }
    }
  }

  return new Response(
    JSON.stringify({ ok: true, dryRun, sent: sentCount, checked: tasksById.size, report }),
    { headers: { 'Content-Type': 'application/json' } },
  )
})
